# Generated by Django 3.0.1 on 2020-01-01 17:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convo_text', models.CharField(max_length=100)),
                ('convo_audio', models.FileField(upload_to=app.models.user_directory_path)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
    ]
