# Generated by Django 3.0.2 on 2020-01-03 16:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationEncryptedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convo_audio', models.FileField(upload_to=app.models.user_directory_path, verbose_name='Conversation Audio File')),
                ('convo_encrypted', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Conversation Hash')),
            ],
            options={
                'verbose_name': 'Encrypted Conversation',
                'verbose_name_plural': 'Encrypted Conversations',
            },
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='convo_audio',
            field=models.FileField(upload_to=app.models.user_directory_path, verbose_name='Conversation Audio File'),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='convo_text',
            field=models.CharField(max_length=100, verbose_name='Conversation Text'),
        ),
    ]
